### ISSUE TITLE
[Bug]: 使用hexo官方方法建站后，部署报错

### ISSUE THREAD

**Issue by sysfox** [valor-x/hexo-theme-solitude#231]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Mac/Linux

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

运行hexo g后报错，回滚回solitude1.7.14无用

### 终端日志 📒

ERROR Render HTML failed: tags/index.html
SyntaxError: Unexpected token (105:4)
    at pp$4.raise (/vercel/path0/node_modules/acorn/dist/acorn.js:2488:13)
    at pp.unexpected (/vercel/path0/node_modules/acorn/dist/acorn.js:623:8)
    at pp$3.parseIdent (/vercel/path0/node_modules/acorn/dist/acorn.js:2445:10)
    at pp$3.parsePropertyName (/vercel/path0/node_modules/acorn/dist/acorn.js:2265:99)
    at pp$3.parseObj (/vercel/path0/node_modules/acorn/dist/acorn.js:2188:12)
    at pp$3.parseExprAtom (/vercel/path0/node_modules/acorn/dist/acorn.js:1994:17)
    at pp$3.parseExprSubscripts (/vercel/path0/node_modules/acorn/dist/acorn.js:1872:19)
    at pp$3.parseMaybeUnary (/vercel/path0/node_modules/acorn/dist/acorn.js:1849:17)
    at pp$3.parseExprOps (/vercel/path0/node_modules/acorn/dist/acorn.js:1791:19)
    at pp$3.parseMaybeConditional (/vercel/path0/node_modules/acorn/dist/acorn.js:1774:19)
    at pp$3.parseMaybeAssign (/vercel/path0/node_modules/acorn/dist/acorn.js:1750:19)
    at pp$1.parseVar (/vercel/path0/node_modules/acorn/dist/acorn.js:1087:26)
    at pp$1.parseVarStatement (/vercel/path0/node_modules/acorn/dist/acorn.js:972:8)
    at pp$1.parseStatement (/vercel/path0/node_modules/acorn/dist/acorn.js:751:17)
    at pp$1.parseBlock (/vercel/path0/node_modules/acorn/dist/acorn.js:1040:23)
    at pp$1.parseStatement (/vercel/path0/node_modules/acorn/dist/acorn.js:754:31)
ERROR Render HTML failed: categories/index.html
SyntaxError: Unexpected token (105:4)
    at pp$4.raise (/vercel/path0/node_modules/acorn/dist/acorn.js:2488:13)
    at pp.unexpected (/vercel/path0/node_modules/acorn/dist/acorn.js:623:8)
    at pp$3.parseIdent (/vercel/path0/node_modules/acorn/dist/acorn.js:2445:10)
    at pp$3.parsePropertyName (/vercel/path0/node_modules/acorn/dist/acorn.js:2265:99)
    at pp$3.parseObj (/vercel/path0/node_modules/acorn/dist/acorn.js:2188:12)
    at pp$3.parseExprAtom (/vercel/path0/node_modules/acorn/dist/acorn.js:1994:17)
    at pp$3.parseExprSubscripts (/vercel/path0/node_modules/acorn/dist/acorn.js:1872:19)
    at pp$3.parseMaybeUnary (/vercel/path0/node_modules/acorn/dist/acorn.js:1849:17)
    at pp$3.parseExprOps (/vercel/path0/node_modules/acorn/dist/acorn.js:1791:19)
    at pp$3.parseMaybeConditional (/vercel/path0/node_modules/acorn/dist/acorn.js:1774:19)
    at pp$3.parseMaybeAssign (/vercel/path0/node_modules/acorn/dist/acorn.js:1750:19)
    at pp$1.parseVar (/vercel/path0/node_modules/acorn/dist/acorn.js:1087:26)
    at pp$1.parseVarStatement (/vercel/path0/node_modules/acorn/dist/acorn.js:972:8)
    at pp$1.parseStatement (/vercel/path0/node_modules/acorn/dist/acorn.js:751:17)
    at pp$1.parseBlock (/vercel/path0/node_modules/acorn/dist/acorn.js:1040:23)
    at pp$1.parseStatement (/vercel/path0/node_modules/acorn/dist/acorn.js:754:31)
ERROR 
SyntaxError: Unexpected token (105:4)
    at pp$4.raise (/vercel/path0/node_modules/acorn/dist/acorn.js:2488:13)
    at pp.unexpected (/vercel/path0/node_modules/acorn/dist/acorn.js:623:8)
    at pp$3.parseIdent (/vercel/path0/node_modules/acorn/dist/acorn.js:2445:10)
    at pp$3.parsePropertyName (/vercel/path0/node_modules/acorn/dist/acorn.js:2265:99)
    at pp$3.parseObj (/vercel/path0/node_modules/acorn/dist/acorn.js:2188:12)
    at pp$3.parseExprAtom (/vercel/path0/node_modules/acorn/dist/acorn.js:1994:17)
    at pp$3.parseExprSubscripts (/vercel/path0/node_modules/acorn/dist/acorn.js:1872:19)
    at pp$3.parseMaybeUnary (/vercel/path0/node_modules/acorn/dist/acorn.js:1849:17)
    at pp$3.parseExprOps (/vercel/path0/node_modules/acorn/dist/acorn.js:1791:19)
    at pp$3.parseMaybeConditional (/vercel/path0/node_modules/acorn/dist/acorn.js:1774:19)
    at pp$3.parseMaybeAssign (/vercel/path0/node_modules/acorn/dist/acorn.js:1750:19)
    at pp$1.parseVar (/vercel/path0/node_modules/acorn/dist/acorn.js:1087:26)
    at pp$1.parseVarStatement (/vercel/path0/node_modules/acorn/dist/acorn.js:972:8)
    at pp$1.parseStatement (/vercel/path0/node_modules/acorn/dist/acorn.js:751:17)
    at pp$1.parseBlock (/vercel/path0/node_modules/acorn/dist/acorn.js:1040:23)
    at pp$1.parseStatement (/vercel/path0/node_modules/acorn/dist/acorn.js:754:31)
ERROR 
SyntaxError: Unexpected token (105:4)
    at pp$4.raise (/vercel/path0/node_modules/acorn/dist/acorn.js:2488:13)
    at pp.unexpected (/vercel/path0/node_modules/acorn/dist/acorn.js:623:8)
    at pp$3.parseIdent (/vercel/path0/node_modules/acorn/dist/acorn.js:2445:10)
    at pp$3.parsePropertyName (/vercel/path0/node_modules/acorn/dist/acorn.js:2265:99)
    at pp$3.parseObj (/vercel/path0/node_modules/acorn/dist/acorn.js:2188:12)
    at pp$3.parseExprAtom (/vercel/path0/node_modules/acorn/dist/acorn.js:1994:17)
    at pp$3.parseExprSubscripts (/vercel/path0/node_modules/acorn/dist/acorn.js:1872:19)
    at pp$3.parseMaybeUnary (/vercel/path0/node_modules/acorn/dist/acorn.js:1849:17)
    at pp$3.parseExprOps (/vercel/path0/node_modules/acorn/dist/acorn.js:1791:19)
    at pp$3.parseMaybeConditional (/vercel/path0/node_modules/acorn/dist/acorn.js:1774:19)
    at pp$3.parseMaybeAssign (/vercel/path0/node_modules/acorn/dist/acorn.js:1750:19)
    at pp$1.parseVar (/vercel/path0/node_modules/acorn/dist/acorn.js:1087:26)
    at pp$1.parseVarStatement (/vercel/path0/node_modules/acorn/dist/acorn.js:972:8)
    at pp$1.parseStatement (/vercel/path0/node_modules/acorn/dist/acorn.js:751:17)
    at pp$1.parseBlock (/vercel/path0/node_modules/acorn/dist/acorn.js:1040:23)
    at pp$1.parseStatement (/vercel/path0/node_modules/acorn/dist/acorn.js:754:31)

**Comment by sysfox** [comment]
另：
landscaoe等其他主题生成正常，应该是solitude的问题

**Comment by efuo** [comment]
生成失败，hexo clean，然后执行 hexo se -d

**Comment by efuo** [comment]
请提供有用的信息

**Comment by efuo** [comment]
你是不是自己新建了 tags 、 categories 、archives页面？主题内置无需新建

**Comment by sysfox** [comment]
> 你是不是自己新建了 tags 、 categories 、archives页面？主题内置无需新建

没有，完全新建站点

**Comment by sysfox** [comment]
> 生成失败，hexo clean，然后执行 hexo se -d

我测试一下

**Comment by efuo** [comment]
装 stylus 和 pug了吗

**Comment by sysfox** [comment]
> 装 stylus 和 pug了吗

装了

**Comment by sysfox** [comment]
> 生成失败，hexo clean，然后执行 hexo se -d

从头测试过了，无效

**Comment by efuo** [comment]
你把debug结果放出来

> > 生成失败，hexo clean，然后执行 hexo se -d
> 
> 从头测试过了，无效

**Comment by efuo** [comment]
加tg群问也可以

**Comment by sysfox** [comment]
更新版本1.8.5，问题已解决
